version: "3.8"
services:
    clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
            - "8123:8123"
            - "9000:9000"
        volumes:
            - clickhouse_data:/var/lib/clickhouse
            - ./config:/etc/clickhouse-server/config.d
            - ./users:/etc/clickhouse-server/users.d
        environment:
            - CLICKHOUSE_USER=default
            - CLICKHOUSE_PASSWORD=
            - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
            - CLICKHOUSE_LOG_LEVEL=trace
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
volumes:
    clickhouse_data:
